name = "phyto-large-upload"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
MAX_FILE_SIZE = 5368709120  # 5GB

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "phyto-uploads"
preview_bucket_name = "phyto-uploads-preview"

[observability]
enabled = true
